apiVersion: extensions/v1
kind: Deployment
metadata:
  name: infracoders-logging-fluentbit
  labels:
    app: infracoders-logging-fluentbit
spec:
  replicas: 1
  selector:
    matchLabels:
      labels:
        app: infracoders-logging-fluentbit
  template:
    metadata:
      labels:
        app: infracoders-logging-fluentbit
    spec:
      containers:
      - name: infracoders-logging
        image: bostjanbozic/infracoders-logging:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: app-logs
            mountPath: /data/infracoders/logs
      - name: fluentbit-logging
        image: fluent/fluent-bit:latest
        imagePullPolicy: Always
        env:
          - name: LOG_NAME
            value: "infracoders_logs_fluentbit"
        volumeMounts:
          - name: app-logs
            mountPath: /data/infracoders/logs
          - name: config-volume
            mountPath: /fluent-bit/etc

      volumes:
        - name: app-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: infracoders-logs-config-fluentbit
