apiVersion: v1
kind: ConfigMap
metadata:
  name: infracoders-logs-config
data:
  fluent.conf: |
    <source>
      @type tail
      format csv
      delimiter ;
      keys timestamp,message,number
      types message:string,number:integer
      path /data/infracoders/logs/infracoders_log_*
      path_key tailed_infracoders_log_path
      pos_file /data/infracoders/infracoders_logs.pos
      tag infracoders
    </source>
    <match infracoders>
      @id elasticsearch
      @type elasticsearch
      type_name _doc
      include_tag_key true
      host elasticsearch
      port 9200
      scheme http
      index_name "#{ENV['LOG_NAME']}.${tag}.%Y%m%d%H"
      <buffer tag, time>
        timekey 30
        timekey_wait 30
      </buffer>
    </match>