apiVersion: v1
kind: ConfigMap
metadata:
  name: infracoders-logs-config-fluentd
data:
  fluentd.conf: |
    <source>
      @type tail
      <parse>
        @type csv
        delimiter ;
        keys timestamp,message,number
        types message:string,number:integer
      </parse>
      path /data/infracoders/logs/infracoders_log_fluentd_*
      path_key infracoders_fluentd_log_path
      pos_file /data/infracoders/infracoders_fluentd_logs.pos
      tag infracoders_fluentd
    </source>

    <filter infracoders_fluentd>
      @type record_transformer
      <record>
        host_param "#{Socket.gethostname}"
      </record>
    </filter>

    <match infracoders_fluentd>
      @id elasticsearch
      @type elasticsearch
      type_name _doc
      include_tag_key true
      host elasticsearch
      port 9200
      scheme http
      index_name "#{ENV['LOG_NAME']}.${tag}.%Y%m%d%H"
      <buffer tag, time>
        timekey 30
        timekey_wait 10
      </buffer>
    </match>
    