apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: infracoders-logging
  labels:
    app: infracoders-logging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: infracoders-logging
    spec:
      containers:
      - name: infracoders-logging
        image: bostjanbozic/infracoders-logging:latest
        volumeMounts:
          - name: app-logs
            mountPath: /data/infracoders/logs
      - name: fluentd-logging
        image: bostjanbozic/fluentd:latest
        imagePullPolicy: Always
        env:
          - name: FLUENTD_ARGS
            value: -c /fluentd/etc/fluent.conf -p /fluentd/plugins
          - name: LOG_NAME
            value: "infracoders_logs"
        volumeMounts:
          - name: app-logs
            mountPath: /data/infracoders/logs
          - name: config-volume
            mountPath: /fluentd/etc

      volumes:
        - name: app-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: infracoders-logs-config
