apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: node
spec:
  selector:
    component: elasticsearch
    role: node
  ports:
  - name: http
    port: 9200
