name: fluentd build and push

on:
  push:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    env:
      working-directory: ./infracoders-VI/fluentd
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code
      
      - name: post path
        run: pwd
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: bostjanbozic/fluentd
          tags: 0.0.2, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASS }}
