name: logging-example build and push

on:
  push:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    env:
      working-directory: ./infracoders-VI/logging-example
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: bostjanbozic/infracoders-logging
          tags: 0.0.2, latest
          registry: docker.io
          dockerfile: ./infracoders-VI/logging-example/Dockerfile
          directory: ./infracoders-VI/logging-example
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASS }}
