apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
    role: node
spec:
  selector:
    component: elasticsearch
    role: node
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
