apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    k8s-app: kibana-infracoders
  ports:
  - name: http
    nodePort: 31000
    port: 5601
    targetPort: http
  type: NodePort